[project]
name = "documentation"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "ai-scribe",
  "canvas>=0.44.2",
  "click>=8.2.1",
  "markdown-it-py[plugins]>=3.0.0",
  "requests>=2.32.4",
  "types-requests>=2.32.4.20250611",
]

[tool.uv]
override-dependencies = ["canvas>=0.44.2"]

[tool.uv.sources]
ai-scribe = { git = "https://github.com/Medical-Software-Foundation/canvas.git", subdirectory = "extensions/ai-scribe", rev = "main" }

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "mypy-extensions>=1.1.0,<2",
    "ruff>=0.13.0",
    "setuptools>=80.9.0",
    "types-requests>=2.32.4.20250611",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
ignore = [
  "D100", # Missing docstring in public module
  "D101", # Missing docstring in public class
  "D102", # Missing docstring in public method
  "D103", # Missing docstring in public function
  "D104", # Missing docstring in public package
  "D105", # Missing docstring in magic method
  "D106", # Missing docstring in public nested class
  "D107", # Missing docstring in __init__
  "D200", # One-line docstring should fit on one line
  "D205", # 1 blank line required between summary line and description
  "D212", # Multi-line docstring summary should start at the first line
  "D402", # First line should not be the function's signature
  "D415", # First line should end with a period, question mark, or exclamation point
  "D417", # Missing argument description in the docstring for ...
  "E501", # Line too long ({width} > {limit})
]
select = [
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "D",   # pydocstyle
  "E",   # pycodestyle errors
  "F",   # Pyflakes
  "I",   # isort
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["typer.Argument", "typer.Option"]

[tool.ruff.lint.pydocstyle]
convention = "google"
