"""
Script that creates FHIR service base URL JSON files for all customer instances.

This script has inline dependencies specified, so it does not require a pyproject.toml file to use
with uv. The only prerequisite is that uv is installed.

This script requires three input files that can be generated by executing the following SQL query
against the Canvas instances in the three customer release channels:

SELECT org.id, org.full_name, address.line1, address.line2, address.city, address.state_code, address.postal_code FROM api_organizationaddress as address INNER JOIN api_organization as org ON address.organization_id = org.id;

Use the "query_instances" Django command in the Console to run these SQL queries.

Steps for updating the FHIR service base URLs in the documentation repository:

1. Create a branch in the documentation repository.

2. Run the above SQL command against instances in the three customer release channels, and output
   the data to three files in your working directory:

   dev_instances.csv
   staging_instances.csv
   prod_instances.csv

3. Run the script:

   uv run fhir_service_base_urls.py dev_instances.csv staging_instances.csv prod_instances.csv fhir-service-base-urls-nonproduction.json fhir-service-base-urls-production.json

4. Move or copy the created JSON output files into the "_static" directory in the documentation
   repository. If you used the filenames in the example, then the files you move will replace the
   existing files. If you did not use the filenames in the example, make sure you rename your files
   so that you overwrite the existing files in "_static".

5. Create a PR from your branch and merge it.
"""

# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "fhir-resources==8.2.0",
# ]
# ///

import argparse
import csv
import uuid
from collections.abc import Mapping
from typing import Any

from fhir.resources.R4B.bundle import Bundle, BundleEntry
from fhir.resources.R4B.endpoint import Endpoint
from fhir.resources.R4B.organization import Organization


def load_orgs(
    dev_file: str, staging_file: str, prod_file: str
) -> dict[str, dict[str, Any]]:
    """Read three CSV files and organize into a single dict keyed by org_name."""
    orgs: dict[str, dict[str, Any]] = {}
    org_identifier_value_counter = 1
    customer_org_ids: dict[str, str] = {}

    files_and_types = [
        (dev_file, "dev"),
        (staging_file, "staging"),
        (prod_file, "prod"),
    ]

    for filepath, org_type in files_and_types:
        with open(filepath, newline="") as f:
            reader = csv.reader(f)
            for row in reader:
                (
                    _row_num,
                    customer_identifier,
                    _,
                    _org_id,
                    org_name,
                    line1,
                    line2,
                    city,
                    state,
                    postal_code,
                ) = row

                address = {
                    "line1": line1.strip(),
                    "line2": line2.strip(),
                    "city": city.strip(),
                    "state": state.strip(),
                    "postal_code": postal_code.strip(),
                }

                org_name = org_name.strip()
                org_id = _org_id.strip()
                customer_identifier = customer_identifier.strip()

                if customer_identifier in customer_org_ids:
                    if customer_org_ids[customer_identifier] != org_id:
                        raise RuntimeError(
                            f"Customer identifier '{customer_identifier}' is associated with "
                            f"multiple org_ids: '{customer_org_ids[customer_identifier]}' and '{org_id}'"
                        )
                else:
                    customer_org_ids[customer_identifier] = org_id

                if org_name not in orgs:
                    orgs[org_name] = {
                        "id": str(uuid.uuid4()),
                        "identifier_value": str(org_identifier_value_counter),
                        "addresses": [],
                        "customer_identifiers": [],
                    }
                    org_identifier_value_counter += 1

                if address not in orgs[org_name]["addresses"]:
                    orgs[org_name]["addresses"].append(address)

                customer = {"value": customer_identifier, "type": org_type}
                if customer not in orgs[org_name]["customer_identifiers"]:
                    orgs[org_name]["customer_identifiers"].append(customer)

    return orgs


def build_bundle(orgs: Mapping[str, Mapping[str, Any]], mode: str) -> Bundle:
    """Build a FHIR Bundle with Endpoint and Organization resources."""
    entries: list[BundleEntry] = []

    for org_name, org_data in sorted(orgs.items()):
        matching_customers = [
            c
            for c in org_data["customer_identifiers"]
            if (mode == "prod" and c["type"] == "prod")
            or (mode == "nonprod" and c["type"] in ("dev", "staging"))
        ]

        if not matching_customers:
            continue

        endpoint_ids = []
        for customer in matching_customers:
            endpoint = Endpoint.model_validate(
                {
                    "id": str(uuid.uuid4()),
                    "status": "active",
                    "connectionType": {
                        "system": "http://terminology.hl7.org/CodeSystem/endpoint-connection-type",
                        "code": "hl7-fhir-rest",
                        "display": "HL7 FHIR",
                    },
                    "payloadType": [{"text": "Canvas FHIR Service Base URL"}],
                    "address": f"https://fumage-{customer['value']}.canvasmedical.com",
                }
            )
            entries.append(
                BundleEntry.model_validate(
                    {"resource": endpoint, "fullUrl": f"urn:uuid:{endpoint.id}"}
                )
            )
            endpoint_ids.append(endpoint.id)

        organization = Organization.model_validate(
            {
                "id": org_data["id"],
                "identifier": [
                    {
                        "system": "http://canvasmedical.com",
                        "value": org_data["identifier_value"],
                    }
                ],
                "name": org_name,
                "address": [
                    {
                        "line": [
                            l
                            for l in (address["line1"], address["line2"])
                            if l
                        ],
                        "city": address["city"],
                        "state": address["state"],
                        "postalCode": address["postal_code"],
                    }
                    for address in org_data["addresses"]
                ],
                "endpoint": [
                    {"reference": f"Endpoint/{e}"}
                    for e in endpoint_ids
                ],
            }
        )
        entries.append(
            BundleEntry.model_validate(
                {"resource": organization, "fullUrl": f"urn:uuid:{organization.id}"}
            )
        )

    return Bundle(type="collection", entry=entries)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create FHIR service base URLs for all customer instances"
    )
    parser.add_argument("dev_instances_file", help="CSV file for dev instances")
    parser.add_argument("staging_instances_file", help="CSV file for staging instances")
    parser.add_argument("prod_instances_file", help="CSV file for prod instances")
    parser.add_argument("nonprod_output_file", help="Output file for nonprod bundle")
    parser.add_argument("prod_output_file", help="Output file for prod bundle")
    args = parser.parse_args()

    orgs = load_orgs(
        args.dev_instances_file, args.staging_instances_file, args.prod_instances_file
    )

    for mode, output_file in [
        ("nonprod", args.nonprod_output_file),
        ("prod", args.prod_output_file),
    ]:
        bundle = build_bundle(orgs, mode)
        with open(output_file, "w") as f:
            f.write(bundle.model_dump_json(indent=2, exclude_none=True))


if __name__ == "__main__":
    main()
