name: Generate Docs for Example Plugins

on:
  workflow_dispatch:
    inputs:
      plugins_changed:
        required: true
        type: string

jobs:
  generate-example-plugin-docs:
    runs-on: ubuntu-latest
    steps:
      # Webhook sender should only send if the branch merged into was main
      # Webhook sender should specify:
      # - plugins_changed
      - name: Log plugins changed
        run: |
          echo "plugins changed: ${{ inputs.plugins_changed }}"
      - name: Checkout the docs repo
        uses: actions/checkout@v4  
      - name: Checkout the canvas-plugins repo
        run: |
          git clone https://github.com/canvas-medical/canvas-plugins.git
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Execute content generation script for each plugin with changes
        run: |
          pwd
          echo "ruby generate_example_plugin_docs.rb ${{ inputs.plugins_changed }}"
      - name: Open pull request with files generated by script
        run: |
          echo "plugins changed: ${{ inputs.plugins_changed }}"
